# https://bevyengine.org/learn/book/getting-started/setup/

# Install mold sudo pacman -S mold

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=/usr/bin/mold", "-Z", "share-generics=y"]

